package com.emc.metrics.mobile;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

public final class Metrics {
  private Metrics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetricOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required .Metric.MetricName name = 2;
    boolean hasName();
    Metrics.Metric.MetricName getName();
    Metrics.Metric.MetricNameOrBuilder getNameOrBuilder();
    
    // required string valueName = 3;
    boolean hasValueName();
    String getValueName();
    
    // required .Metric.ValueType valueType = 4;
    boolean hasValueType();
    Metrics.Metric.ValueType getValueType();
    
    // optional int64 intValue = 5;
    boolean hasIntValue();
    long getIntValue();
    
    // optional double floatValue = 6;
    boolean hasFloatValue();
    double getFloatValue();
    
    // optional string StringValue = 7;
    boolean hasStringValue();
    String getStringValue();
  }
  public static final class Metric extends
      com.google.protobuf.GeneratedMessage
      implements MetricOrBuilder {
    // Use Metric.newBuilder() to construct.
    private Metric(Builder builder) {
      super(builder);
    }
    private Metric(boolean noInit) {}
    
    private static final Metric defaultInstance;
    public static Metric getDefaultInstance() {
      return defaultInstance;
    }
    
    public Metric getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Metrics.internal_static_Metric_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Metrics.internal_static_Metric_fieldAccessorTable;
    }
    
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      INT(0, 0),
      FLOAT(1, 1),
      STRING(2, 2),
      ;
      
      public static final int INT_VALUE = 0;
      public static final int FLOAT_VALUE = 1;
      public static final int STRING_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static ValueType valueOf(int value) {
        switch (value) {
          case 0: return INT;
          case 1: return FLOAT;
          case 2: return STRING;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Metrics.Metric.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ValueType[] VALUES = {
        INT, FLOAT, STRING, 
      };
      
      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ValueType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Metric.ValueType)
    }
    
    public interface MetricNameOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string group = 1;
      boolean hasGroup();
      String getGroup();
      
      // required string type = 2;
      boolean hasType();
      String getType();
      
      // required string name = 3;
      boolean hasName();
      String getName();
      
      // optional string scope = 4;
      boolean hasScope();
      String getScope();
    }
    public static final class MetricName extends
        com.google.protobuf.GeneratedMessage
        implements MetricNameOrBuilder {
      // Use MetricName.newBuilder() to construct.
      private MetricName(Builder builder) {
        super(builder);
      }
      private MetricName(boolean noInit) {}
      
      private static final MetricName defaultInstance;
      public static MetricName getDefaultInstance() {
        return defaultInstance;
      }
      
      public MetricName getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Metrics.internal_static_Metric_MetricName_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Metrics.internal_static_Metric_MetricName_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string group = 1;
      public static final int GROUP_FIELD_NUMBER = 1;
      private java.lang.Object group_;
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGroup() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            group_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string type = 2;
      public static final int TYPE_FIELD_NUMBER = 2;
      private java.lang.Object type_;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            type_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string name = 3;
      public static final int NAME_FIELD_NUMBER = 3;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string scope = 4;
      public static final int SCOPE_FIELD_NUMBER = 4;
      private java.lang.Object scope_;
      public boolean hasScope() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getScope() {
        java.lang.Object ref = scope_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            scope_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getScopeBytes() {
        java.lang.Object ref = scope_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          scope_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        group_ = "";
        type_ = "";
        name_ = "";
        scope_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasGroup()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getGroupBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getNameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getScopeBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getGroupBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getNameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getScopeBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static Metrics.Metric.MetricName parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Metrics.Metric.MetricName parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Metrics.Metric.MetricName parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Metrics.Metric.MetricName parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Metrics.Metric.MetricName parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Metrics.Metric.MetricName parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static Metrics.Metric.MetricName parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Metrics.Metric.MetricName parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Metrics.Metric.MetricName parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Metrics.Metric.MetricName parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Metrics.Metric.MetricName prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements Metrics.Metric.MetricNameOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Metrics.internal_static_Metric_MetricName_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Metrics.internal_static_Metric_MetricName_fieldAccessorTable;
        }
        
        // Construct using Metrics.Metric.MetricName.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          group_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          scope_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Metrics.Metric.MetricName.getDescriptor();
        }
        
        public Metrics.Metric.MetricName getDefaultInstanceForType() {
          return Metrics.Metric.MetricName.getDefaultInstance();
        }
        
        public Metrics.Metric.MetricName build() {
          Metrics.Metric.MetricName result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private Metrics.Metric.MetricName buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          Metrics.Metric.MetricName result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public Metrics.Metric.MetricName buildPartial() {
          Metrics.Metric.MetricName result = new Metrics.Metric.MetricName(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.group_ = group_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.scope_ = scope_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Metrics.Metric.MetricName) {
            return mergeFrom((Metrics.Metric.MetricName)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(Metrics.Metric.MetricName other) {
          if (other == Metrics.Metric.MetricName.getDefaultInstance()) return this;
          if (other.hasGroup()) {
            setGroup(other.getGroup());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasScope()) {
            setScope(other.getScope());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasGroup()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          if (!hasName()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                group_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                type_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                name_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                scope_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string group = 1;
        private java.lang.Object group_ = "";
        public boolean hasGroup() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getGroup() {
          java.lang.Object ref = group_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            group_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setGroup(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          group_ = value;
          onChanged();
          return this;
        }
        public Builder clearGroup() {
          bitField0_ = (bitField0_ & ~0x00000001);
          group_ = getDefaultInstance().getGroup();
          onChanged();
          return this;
        }
        void setGroup(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          group_ = value;
          onChanged();
        }
        
        // required string type = 2;
        private java.lang.Object type_ = "";
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setType(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        void setType(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
        }
        
        // required string name = 3;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
        }
        
        // optional string scope = 4;
        private java.lang.Object scope_ = "";
        public boolean hasScope() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public String getScope() {
          java.lang.Object ref = scope_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            scope_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setScope(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          scope_ = value;
          onChanged();
          return this;
        }
        public Builder clearScope() {
          bitField0_ = (bitField0_ & ~0x00000008);
          scope_ = getDefaultInstance().getScope();
          onChanged();
          return this;
        }
        void setScope(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000008;
          scope_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:Metric.MetricName)
      }
      
      static {
        defaultInstance = new MetricName(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Metric.MetricName)
    }
    
    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required .Metric.MetricName name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Metrics.Metric.MetricName name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public Metrics.Metric.MetricName getName() {
      return name_;
    }
    public Metrics.Metric.MetricNameOrBuilder getNameOrBuilder() {
      return name_;
    }
    
    // required string valueName = 3;
    public static final int VALUENAME_FIELD_NUMBER = 3;
    private java.lang.Object valueName_;
    public boolean hasValueName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getValueName() {
      java.lang.Object ref = valueName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          valueName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueNameBytes() {
      java.lang.Object ref = valueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        valueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .Metric.ValueType valueType = 4;
    public static final int VALUETYPE_FIELD_NUMBER = 4;
    private Metrics.Metric.ValueType valueType_;
    public boolean hasValueType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public Metrics.Metric.ValueType getValueType() {
      return valueType_;
    }
    
    // optional int64 intValue = 5;
    public static final int INTVALUE_FIELD_NUMBER = 5;
    private long intValue_;
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getIntValue() {
      return intValue_;
    }
    
    // optional double floatValue = 6;
    public static final int FLOATVALUE_FIELD_NUMBER = 6;
    private double floatValue_;
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getFloatValue() {
      return floatValue_;
    }
    
    // optional string StringValue = 7;
    public static final int STRINGVALUE_FIELD_NUMBER = 7;
    private java.lang.Object stringValue_;
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stringValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      timestamp_ = 0L;
      name_ = Metrics.Metric.MetricName.getDefaultInstance();
      valueName_ = "";
      valueType_ = Metrics.Metric.ValueType.INT;
      intValue_ = 0L;
      floatValue_ = 0D;
      stringValue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValueName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValueType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getName().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getValueNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, valueType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, intValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, floatValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getStringValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getValueNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, valueType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, intValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, floatValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getStringValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Metrics.Metric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Metrics.Metric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Metrics.Metric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Metrics.Metric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Metrics.Metric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Metrics.Metric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Metrics.Metric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Metrics.Metric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Metrics.Metric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Metrics.Metric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Metrics.Metric prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Metrics.MetricOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Metrics.internal_static_Metric_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Metrics.internal_static_Metric_fieldAccessorTable;
      }
      
      // Construct using Metrics.Metric.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nameBuilder_ == null) {
          name_ = Metrics.Metric.MetricName.getDefaultInstance();
        } else {
          nameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        valueName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        valueType_ = Metrics.Metric.ValueType.INT;
        bitField0_ = (bitField0_ & ~0x00000008);
        intValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        floatValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Metrics.Metric.getDescriptor();
      }
      
      public Metrics.Metric getDefaultInstanceForType() {
        return Metrics.Metric.getDefaultInstance();
      }
      
      public Metrics.Metric build() {
        Metrics.Metric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Metrics.Metric buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Metrics.Metric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Metrics.Metric buildPartial() {
        Metrics.Metric result = new Metrics.Metric(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.valueName_ = valueName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.valueType_ = valueType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.intValue_ = intValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.floatValue_ = floatValue_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.stringValue_ = stringValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Metrics.Metric) {
          return mergeFrom((Metrics.Metric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Metrics.Metric other) {
        if (other == Metrics.Metric.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        if (other.hasValueName()) {
          setValueName(other.getValueName());
        }
        if (other.hasValueType()) {
          setValueType(other.getValueType());
        }
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasFloatValue()) {
          setFloatValue(other.getFloatValue());
        }
        if (other.hasStringValue()) {
          setStringValue(other.getStringValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasValueName()) {
          
          return false;
        }
        if (!hasValueType()) {
          
          return false;
        }
        if (!getName().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              Metrics.Metric.MetricName.Builder subBuilder = Metrics.Metric.MetricName.newBuilder();
              if (hasName()) {
                subBuilder.mergeFrom(getName());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setName(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              valueName_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              Metrics.Metric.ValueType value = Metrics.Metric.ValueType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                valueType_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              intValue_ = input.readInt64();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              floatValue_ = input.readDouble();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              stringValue_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required .Metric.MetricName name = 2;
      private Metrics.Metric.MetricName name_ = Metrics.Metric.MetricName.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Metrics.Metric.MetricName, Metrics.Metric.MetricName.Builder, Metrics.Metric.MetricNameOrBuilder> nameBuilder_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public Metrics.Metric.MetricName getName() {
        if (nameBuilder_ == null) {
          return name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      public Builder setName(Metrics.Metric.MetricName value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setName(
          Metrics.Metric.MetricName.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeName(Metrics.Metric.MetricName value) {
        if (nameBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              name_ != Metrics.Metric.MetricName.getDefaultInstance()) {
            name_ =
              Metrics.Metric.MetricName.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = Metrics.Metric.MetricName.getDefaultInstance();
          onChanged();
        } else {
          nameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public Metrics.Metric.MetricName.Builder getNameBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      public Metrics.Metric.MetricNameOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Metrics.Metric.MetricName, Metrics.Metric.MetricName.Builder, Metrics.Metric.MetricNameOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Metrics.Metric.MetricName, Metrics.Metric.MetricName.Builder, Metrics.Metric.MetricNameOrBuilder>(
                  name_,
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      
      // required string valueName = 3;
      private java.lang.Object valueName_ = "";
      public boolean hasValueName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getValueName() {
        java.lang.Object ref = valueName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          valueName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValueName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        valueName_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        valueName_ = getDefaultInstance().getValueName();
        onChanged();
        return this;
      }
      void setValueName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        valueName_ = value;
        onChanged();
      }
      
      // required .Metric.ValueType valueType = 4;
      private Metrics.Metric.ValueType valueType_ = Metrics.Metric.ValueType.INT;
      public boolean hasValueType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public Metrics.Metric.ValueType getValueType() {
        return valueType_;
      }
      public Builder setValueType(Metrics.Metric.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        valueType_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        valueType_ = Metrics.Metric.ValueType.INT;
        onChanged();
        return this;
      }
      
      // optional int64 intValue = 5;
      private long intValue_ ;
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getIntValue() {
        return intValue_;
      }
      public Builder setIntValue(long value) {
        bitField0_ |= 0x00000010;
        intValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        intValue_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double floatValue = 6;
      private double floatValue_ ;
      public boolean hasFloatValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getFloatValue() {
        return floatValue_;
      }
      public Builder setFloatValue(double value) {
        bitField0_ |= 0x00000020;
        floatValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        floatValue_ = 0D;
        onChanged();
        return this;
      }
      
      // optional string StringValue = 7;
      private java.lang.Object stringValue_ = "";
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStringValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        stringValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      void setStringValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        stringValue_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Metric)
    }
    
    static {
      defaultInstance = new Metric(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Metric)
  }
  
  public interface MetricListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .Metric metric = 1;
    java.util.List<Metrics.Metric> 
        getMetricList();
    Metrics.Metric getMetric(int index);
    int getMetricCount();
    java.util.List<? extends Metrics.MetricOrBuilder> 
        getMetricOrBuilderList();
    Metrics.MetricOrBuilder getMetricOrBuilder(
        int index);
  }
  public static final class MetricList extends
      com.google.protobuf.GeneratedMessage
      implements MetricListOrBuilder {
    // Use MetricList.newBuilder() to construct.
    private MetricList(Builder builder) {
      super(builder);
    }
    private MetricList(boolean noInit) {}
    
    private static final MetricList defaultInstance;
    public static MetricList getDefaultInstance() {
      return defaultInstance;
    }
    
    public MetricList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Metrics.internal_static_MetricList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Metrics.internal_static_MetricList_fieldAccessorTable;
    }
    
    // repeated .Metric metric = 1;
    public static final int METRIC_FIELD_NUMBER = 1;
    private java.util.List<Metrics.Metric> metric_;
    public java.util.List<Metrics.Metric> getMetricList() {
      return metric_;
    }
    public java.util.List<? extends Metrics.MetricOrBuilder> 
        getMetricOrBuilderList() {
      return metric_;
    }
    public int getMetricCount() {
      return metric_.size();
    }
    public Metrics.Metric getMetric(int index) {
      return metric_.get(index);
    }
    public Metrics.MetricOrBuilder getMetricOrBuilder(
        int index) {
      return metric_.get(index);
    }
    
    private void initFields() {
      metric_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getMetricCount(); i++) {
        if (!getMetric(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < metric_.size(); i++) {
        output.writeMessage(1, metric_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < metric_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, metric_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Metrics.MetricList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Metrics.MetricList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Metrics.MetricList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Metrics.MetricList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Metrics.MetricList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Metrics.MetricList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Metrics.MetricList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Metrics.MetricList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Metrics.MetricList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Metrics.MetricList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Metrics.MetricList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Metrics.MetricListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Metrics.internal_static_MetricList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Metrics.internal_static_MetricList_fieldAccessorTable;
      }
      
      // Construct using Metrics.MetricList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMetricFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (metricBuilder_ == null) {
          metric_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          metricBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Metrics.MetricList.getDescriptor();
      }
      
      public Metrics.MetricList getDefaultInstanceForType() {
        return Metrics.MetricList.getDefaultInstance();
      }
      
      public Metrics.MetricList build() {
        Metrics.MetricList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Metrics.MetricList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Metrics.MetricList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Metrics.MetricList buildPartial() {
        Metrics.MetricList result = new Metrics.MetricList(this);
        int from_bitField0_ = bitField0_;
        if (metricBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            metric_ = java.util.Collections.unmodifiableList(metric_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.metric_ = metric_;
        } else {
          result.metric_ = metricBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Metrics.MetricList) {
          return mergeFrom((Metrics.MetricList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Metrics.MetricList other) {
        if (other == Metrics.MetricList.getDefaultInstance()) return this;
        if (metricBuilder_ == null) {
          if (!other.metric_.isEmpty()) {
            if (metric_.isEmpty()) {
              metric_ = other.metric_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMetricIsMutable();
              metric_.addAll(other.metric_);
            }
            onChanged();
          }
        } else {
          if (!other.metric_.isEmpty()) {
            if (metricBuilder_.isEmpty()) {
              metricBuilder_.dispose();
              metricBuilder_ = null;
              metric_ = other.metric_;
              bitField0_ = (bitField0_ & ~0x00000001);
              metricBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetricFieldBuilder() : null;
            } else {
              metricBuilder_.addAllMessages(other.metric_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getMetricCount(); i++) {
          if (!getMetric(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              Metrics.Metric.Builder subBuilder = Metrics.Metric.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMetric(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .Metric metric = 1;
      private java.util.List<Metrics.Metric> metric_ =
        java.util.Collections.emptyList();
      private void ensureMetricIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          metric_ = new java.util.ArrayList<Metrics.Metric>(metric_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Metrics.Metric, Metrics.Metric.Builder, Metrics.MetricOrBuilder> metricBuilder_;
      
      public java.util.List<Metrics.Metric> getMetricList() {
        if (metricBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metric_);
        } else {
          return metricBuilder_.getMessageList();
        }
      }
      public int getMetricCount() {
        if (metricBuilder_ == null) {
          return metric_.size();
        } else {
          return metricBuilder_.getCount();
        }
      }
      public Metrics.Metric getMetric(int index) {
        if (metricBuilder_ == null) {
          return metric_.get(index);
        } else {
          return metricBuilder_.getMessage(index);
        }
      }
      public Builder setMetric(
          int index, Metrics.Metric value) {
        if (metricBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricIsMutable();
          metric_.set(index, value);
          onChanged();
        } else {
          metricBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMetric(
          int index, Metrics.Metric.Builder builderForValue) {
        if (metricBuilder_ == null) {
          ensureMetricIsMutable();
          metric_.set(index, builderForValue.build());
          onChanged();
        } else {
          metricBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMetric(Metrics.Metric value) {
        if (metricBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricIsMutable();
          metric_.add(value);
          onChanged();
        } else {
          metricBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMetric(
          int index, Metrics.Metric value) {
        if (metricBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricIsMutable();
          metric_.add(index, value);
          onChanged();
        } else {
          metricBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMetric(
          Metrics.Metric.Builder builderForValue) {
        if (metricBuilder_ == null) {
          ensureMetricIsMutable();
          metric_.add(builderForValue.build());
          onChanged();
        } else {
          metricBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMetric(
          int index, Metrics.Metric.Builder builderForValue) {
        if (metricBuilder_ == null) {
          ensureMetricIsMutable();
          metric_.add(index, builderForValue.build());
          onChanged();
        } else {
          metricBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMetric(
          java.lang.Iterable<? extends Metrics.Metric> values) {
        if (metricBuilder_ == null) {
          ensureMetricIsMutable();
          super.addAll(values, metric_);
          onChanged();
        } else {
          metricBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMetric() {
        if (metricBuilder_ == null) {
          metric_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          metricBuilder_.clear();
        }
        return this;
      }
      public Builder removeMetric(int index) {
        if (metricBuilder_ == null) {
          ensureMetricIsMutable();
          metric_.remove(index);
          onChanged();
        } else {
          metricBuilder_.remove(index);
        }
        return this;
      }
      public Metrics.Metric.Builder getMetricBuilder(
          int index) {
        return getMetricFieldBuilder().getBuilder(index);
      }
      public Metrics.MetricOrBuilder getMetricOrBuilder(
          int index) {
        if (metricBuilder_ == null) {
          return metric_.get(index);  } else {
          return metricBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends Metrics.MetricOrBuilder> 
           getMetricOrBuilderList() {
        if (metricBuilder_ != null) {
          return metricBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metric_);
        }
      }
      public Metrics.Metric.Builder addMetricBuilder() {
        return getMetricFieldBuilder().addBuilder(
            Metrics.Metric.getDefaultInstance());
      }
      public Metrics.Metric.Builder addMetricBuilder(
          int index) {
        return getMetricFieldBuilder().addBuilder(
            index, Metrics.Metric.getDefaultInstance());
      }
      public java.util.List<Metrics.Metric.Builder> 
           getMetricBuilderList() {
        return getMetricFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Metrics.Metric, Metrics.Metric.Builder, Metrics.MetricOrBuilder> 
          getMetricFieldBuilder() {
        if (metricBuilder_ == null) {
          metricBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Metrics.Metric, Metrics.Metric.Builder, Metrics.MetricOrBuilder>(
                  metric_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          metric_ = null;
        }
        return metricBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:MetricList)
    }
    
    static {
      defaultInstance = new MetricList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MetricList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Metric_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Metric_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Metric_MetricName_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Metric_MetricName_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MetricList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MetricList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetrics.proto\"\246\002\n\006Metric\022\021\n\ttimestamp\030" +
      "\001 \002(\003\022 \n\004name\030\002 \002(\0132\022.Metric.MetricName\022" +
      "\021\n\tvalueName\030\003 \002(\t\022$\n\tvalueType\030\004 \002(\0162\021." +
      "Metric.ValueType\022\020\n\010intValue\030\005 \001(\003\022\022\n\nfl" +
      "oatValue\030\006 \001(\001\022\023\n\013StringValue\030\007 \001(\t\032F\n\nM" +
      "etricName\022\r\n\005group\030\001 \002(\t\022\014\n\004type\030\002 \002(\t\022\014" +
      "\n\004name\030\003 \002(\t\022\r\n\005scope\030\004 \001(\t\"+\n\tValueType" +
      "\022\007\n\003INT\020\000\022\t\n\005FLOAT\020\001\022\n\n\006STRING\020\002\"%\n\nMetr" +
      "icList\022\027\n\006metric\030\001 \003(\0132\007.Metric"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Metric_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Metric_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Metric_descriptor,
              new java.lang.String[] { "Timestamp", "Name", "ValueName", "ValueType", "IntValue", "FloatValue", "StringValue", },
              Metrics.Metric.class,
              Metrics.Metric.Builder.class);
          internal_static_Metric_MetricName_descriptor =
            internal_static_Metric_descriptor.getNestedTypes().get(0);
          internal_static_Metric_MetricName_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Metric_MetricName_descriptor,
              new java.lang.String[] { "Group", "Type", "Name", "Scope", },
              Metrics.Metric.MetricName.class,
              Metrics.Metric.MetricName.Builder.class);
          internal_static_MetricList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MetricList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MetricList_descriptor,
              new java.lang.String[] { "Metric", },
              Metrics.MetricList.class,
              Metrics.MetricList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
